---

- name: setup
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_user_shell_name }}.yml"
    - "{{ ansible_system | lower }}.yml"
  tags: always

- include_tasks: "{{ item }}"
  with_first_found:
    - "configure_{{ ansible_user_shell_name }}_{{ j_configure_state }}.yml"
    - "configure_default.yml"
  tags:
    - bootstrap
    - bootstrap_j
    - configure
    - configure_j
